# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastCorr <- function(m, ncores = 1L, verbose = TRUE, full = FALSE, diag = TRUE, dist = TRUE) {
    .Call(`_sparseDist_fastCorr`, m, ncores, verbose, full, diag, dist)
}

fastCorr2 <- function(m, m2, ncores = 1L, verbose = TRUE, dist = TRUE) {
    .Call(`_sparseDist_fastCorr2`, m, m2, ncores, verbose, dist)
}

fastCov <- function(m, ncores = 1L, verbose = TRUE, full = FALSE, diag = TRUE, dist = TRUE) {
    .Call(`_sparseDist_fastCov`, m, ncores, verbose, full, diag, dist)
}

fastCov2 <- function(m, m2, ncores = 1L, verbose = TRUE) {
    .Call(`_sparseDist_fastCov2`, m, m2, ncores, verbose)
}

fastJacc2 <- function(m, m2, ncores = 1L, verbose = TRUE, dist = TRUE) {
    .Call(`_sparseDist_fastJacc2`, m, m2, ncores, verbose, dist)
}

fastJacc <- function(m, ncores = 1L, verbose = TRUE, full = FALSE, diag = TRUE, dist = TRUE) {
    .Call(`_sparseDist_fastJacc`, m, ncores, verbose, full, diag, dist)
}

fastWeightedJacc2 <- function(m, m2, ncores = 1L, verbose = TRUE, dist = TRUE) {
    .Call(`_sparseDist_fastWeightedJacc2`, m, m2, ncores, verbose, dist)
}

fastWeightedJacc <- function(m, ncores = 1L, verbose = TRUE, full = FALSE, diag = TRUE, dist = TRUE) {
    .Call(`_sparseDist_fastWeightedJacc`, m, ncores, verbose, full, diag, dist)
}

fastManhattan <- function(m, ncores = 1L, verbose = TRUE, full = FALSE, diag = TRUE) {
    .Call(`_sparseDist_fastManhattan`, m, ncores, verbose, full, diag)
}

fastManhattan2 <- function(m, m2, ncores = 1L, verbose = TRUE, dist = TRUE) {
    .Call(`_sparseDist_fastManhattan2`, m, m2, ncores, verbose, dist)
}

fastEuclidean <- function(m, ncores = 1L, verbose = TRUE, full = FALSE, diag = TRUE) {
    .Call(`_sparseDist_fastEuclidean`, m, ncores, verbose, full, diag)
}

fastEuclidean2 <- function(m, m2, ncores = 1L, verbose = TRUE) {
    .Call(`_sparseDist_fastEuclidean2`, m, m2, ncores, verbose)
}

fastJS <- function(m, ncores = 1L, verbose = TRUE, full = FALSE, diag = TRUE) {
    .Call(`_sparseDist_fastJS`, m, ncores, verbose, full, diag)
}

fastJS2 <- function(m, m2, ncores = 1L, verbose = TRUE) {
    .Call(`_sparseDist_fastJS2`, m, m2, ncores, verbose)
}

