# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

detectCoresCpp <- function() {
    .Call(`_sparseDist_detectCoresCpp`)
}

ompInfoCpp <- function() {
    .Call(`_sparseDist_ompInfoCpp`)
}

snnJaccard <- function(idx, include_self = TRUE, ncores = 1L, verbose = FALSE) {
    .Call(`_sparseDist_snnJaccard`, idx, include_self, ncores, verbose)
}

snnJaccardShared <- function(idx, include_self = TRUE, prune = 0.0, ncores = 1L, verbose = FALSE) {
    .Call(`_sparseDist_snnJaccardShared`, idx, include_self, prune, ncores, verbose)
}

fastCorr <- function(m, ncores = 1L, verbose = TRUE, full = FALSE, diag = TRUE, dist = TRUE) {
    .Call(`_sparseDist_fastCorr`, m, ncores, verbose, full, diag, dist)
}

fastCorr2 <- function(m, m2, ncores = 1L, verbose = TRUE, dist = TRUE) {
    .Call(`_sparseDist_fastCorr2`, m, m2, ncores, verbose, dist)
}

fastCov <- function(m, ncores = 1L, verbose = TRUE, full = FALSE, diag = TRUE) {
    .Call(`_sparseDist_fastCov`, m, ncores, verbose, full, diag)
}

fastCov2 <- function(m, m2, ncores = 1L, verbose = TRUE) {
    .Call(`_sparseDist_fastCov2`, m, m2, ncores, verbose)
}

fastJacc2 <- function(m, m2, ncores = 1L, verbose = TRUE, dist = TRUE) {
    .Call(`_sparseDist_fastJacc2`, m, m2, ncores, verbose, dist)
}

fastJacc <- function(m, ncores = 1L, verbose = TRUE, full = FALSE, diag = TRUE, dist = TRUE) {
    .Call(`_sparseDist_fastJacc`, m, ncores, verbose, full, diag, dist)
}

fastManhattan <- function(m, ncores = 1L, verbose = TRUE, full = FALSE, diag = TRUE) {
    .Call(`_sparseDist_fastManhattan`, m, ncores, verbose, full, diag)
}

fastManhattan2 <- function(m, m2, ncores = 1L, verbose = TRUE) {
    .Call(`_sparseDist_fastManhattan2`, m, m2, ncores, verbose)
}

fastEuclidean <- function(m, ncores = 1L, verbose = TRUE, full = FALSE, diag = TRUE) {
    .Call(`_sparseDist_fastEuclidean`, m, ncores, verbose, full, diag)
}

fastEuclidean2 <- function(m, m2, ncores = 1L, verbose = TRUE) {
    .Call(`_sparseDist_fastEuclidean2`, m, m2, ncores, verbose)
}

fastCosine <- function(m, ncores = 1L, verbose = TRUE, full = FALSE, diag = TRUE, dist = TRUE) {
    .Call(`_sparseDist_fastCosine`, m, ncores, verbose, full, diag, dist)
}

fastCosine2 <- function(m, m2, ncores = 1L, verbose = TRUE, dist = TRUE) {
    .Call(`_sparseDist_fastCosine2`, m, m2, ncores, verbose, dist)
}

fastJS <- function(m, ncores = 1L, verbose = TRUE, full = FALSE, diag = TRUE) {
    .Call(`_sparseDist_fastJS`, m, ncores, verbose, full, diag)
}

fastJS2 <- function(m, m2, ncores = 1L, verbose = TRUE) {
    .Call(`_sparseDist_fastJS2`, m, m2, ncores, verbose)
}

topKBlock <- function(D, k, decreasing, self_row, ncores = 1L) {
    .Call(`_sparseDist_topKBlock`, D, k, decreasing, self_row, ncores)
}

topKRowsAccum <- function(D, k, decreasing, best_idx, best_val, col_offset, self_col, ncores = 1L, tile_rows = 64L) {
    invisible(.Call(`_sparseDist_topKRowsAccum`, D, k, decreasing, best_idx, best_val, col_offset, self_col, ncores, tile_rows))
}

